# Generated by Django 3.2.4 on 2021-06-24 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idEspecie', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de especie')),
                ('nombreEspecie', models.CharField(max_length=50, verbose_name='Nombre de la especie')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del género')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Nombre del género')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('numChip', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero de chip')),
                ('nombreAnimal', models.CharField(max_length=50, verbose_name='Nombre animal')),
                ('edadAnimal', models.IntegerField(verbose_name='Edad animal')),
                ('esterilizado', models.BooleanField(verbose_name='Esterilizado')),
                ('fotografia', models.ImageField(blank=True, upload_to='images', verbose_name='Fotografía animal')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especie', verbose_name='Especie')),
                ('generoAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero', verbose_name='Género animal')),
            ],
            options={
                'db_table': 'core_animal',
            },
        ),
    ]
