# Generated by Django 3.2.3 on 2021-06-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del género')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Nombre del género')),
            ],
        ),
        migrations.RemoveField(
            model_name='animal',
            name='esterilizacion',
        ),
        migrations.AddField(
            model_name='animal',
            name='esterilizado',
            field=models.BooleanField(default=1, verbose_name='Esterilizado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animal',
            name='fotografia',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Fotografía animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='edadAnimal',
            field=models.IntegerField(verbose_name='Edad animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especie', verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='numChip',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero de chip'),
        ),
        migrations.AlterModelTable(
            name='animal',
            table='core_animal',
        ),
        migrations.AlterField(
            model_name='animal',
            name='generoAnimal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero', verbose_name='Género animal'),
        ),
    ]
