# Generated by Django 3.2.4 on 2021-06-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_edadanimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='fotografia',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Fotografía animal'),
        ),
    ]
