# Generated by Django 3.2.4 on 2021-06-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal_fotografia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='numChip',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Numero de chip'),
        ),
    ]
