# Generated by Django 3.2.4 on 2021-06-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_animal_numchip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del género')),
                ('nombreGenero', models.CharField(max_length=50, verbose_name='Nombre del género')),
            ],
        ),
        migrations.AlterField(
            model_name='animal',
            name='generoAnimal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.genero'),
        ),
    ]
